#include "RecentBooksActivity.h"

#include <Bitmap.h>
#include <Epub.h>
#include <Epub/converters/ImageDecoderFactory.h>
#include <Epub/converters/ImageToFramebufferDecoder.h>
#include <FontCacheManager.h>
#include <FsHelpers.h>
#include <GfxRenderer.h>
#include <HalStorage.h>
#include <I18n.h>
#include <JpegToBmpConverter.h>
#include <MangaPanel.h>
#include <Memory.h>
#include <PngToBmpConverter.h>
#include <Xtc.h>

#include <algorithm>
#include <cstdio>
#include <iterator>
#include <memory>

#include "EpubProgressUtil.h"
#include "MappedInputManager.h"
#include "RecentBooksStore.h"
#include "XtcProgressUtil.h"
#include "activities/util/ConfirmationActivity.h"
#include "components/UITheme.h"
#include "components/icons/cover.h"
#include "fontIds.h"

namespace {
constexpr unsigned long LONG_PRESS_MS = 1000;
constexpr int COVER_ASPECT_NUM = 2;
constexpr int COVER_ASPECT_DEN = 3;
constexpr int SHELF_THUMB_WIDTH = 36;
constexpr int SHELF_THUMB_HEIGHT = 54;
constexpr uint32_t THUMB_IDLE_MS = 2000;

// Diagnostic artifact written by HalSystem::checkPanic() to the SD root -- a .txt file the
// library walk would otherwise list as a book.
bool isCrashReportFile(const char* name) { return strcmp(name, "crash_report.txt") == 0; }

// A cached cover thumb is only usable when it is exactly the requested height -- earlier builds
// generated aspect-fill thumbs that could come out TALLER than requested (e.g. 232px for a 226px
// request), which the home screen letterboxes into a white right stripe inside the cover frame.
bool thumbHeightValid(const std::string& thumbPath, const int h) {
  // Width must match the cover box too, not just the height: thumbs generated by an earlier
  // build are exactly `h` tall but narrower, which still needs a crop at draw time -- the slow
  // per-pixel path (~250ms per cover, and clicks are dropped during such a render). Checking
  // only the height let those survive forever.
  const int expectedW = (h * COVER_ASPECT_NUM) / COVER_ASPECT_DEN;
  HalFile f;
  if (!Storage.openFileForRead("LIB", thumbPath, f)) return false;
  Bitmap bmp(f);
  bool ok = bmp.parseHeaders() == BmpReaderError::Ok && bmp.getHeight() == h && bmp.getWidth() == expectedW;
  if (ok) {
    // The header alone does not prove the pixels are there: a generation that ran out of
    // memory (reported from an X3, whose larger viewport leaves less headroom) leaves a
    // truncated file whose header still reads correctly, and it then survives forever because
    // the height matches. Require the full pixel payload -- rows are 4-byte aligned.
    const uint32_t needed = static_cast<uint32_t>(bmp.getRowBytes()) * static_cast<uint32_t>(bmp.getHeight());
    // Compare against the pixel payload only; any sane header size is on top of it.
    if (static_cast<uint32_t>(f.size()) < needed) {
      LOG_DBG("LIB", "Discarding truncated thumb %s (%u < %u bytes)", thumbPath.c_str(), (unsigned)f.size(),
              (unsigned)needed);
      ok = false;
    }
  }
  f.close();
  return ok;
}

// Generate (once) 1-bit BMP cover thumbnails for a manga folder from its first page image, at
// every height that draws one: the Library's cover grid (gridHeight), the home screen's Continue
// Reading card (homeHeight) and the shelves tab (SHELF_THUMB_HEIGHT). Decoding the raw page JPEG
// straight to the framebuffer cost ~430ms per visible manga cover on EVERY render; the cached
// BMPs draw in a few ms via the same fast path as EPUB covers. Returns the [HEIGHT]-templated
// thumb path, or empty on any failure (caller keeps the raw image path -- the old,
// slow-but-working behavior).
//
// homeHeight has to be generated HERE because nothing else can: HomeActivity::loadRecentCovers
// regenerates a missing thumb only for .epub and .xtc, so a manga folder resolves the same
// [HEIGHT] template against a height nobody produced and the card falls back to a placeholder.
// That is the X3 report of missing manga covers on the home screen -- the X4 only appeared to
// work because its 480px-wide grid yields a cell height near Lyra's 226px card, while the X3's
// 528px grid does not. Repeated heights cost nothing: the existing validity check below skips a
// height whose thumb is already on disk.
std::string ensureMangaCoverThumb(const std::string& mangaFolder, const int gridHeight, const int homeHeight,
                                  BmpConvertCancelFn shouldCancel, void* cancelCtx) {
  const manga::MangaBook book(mangaFolder);
  const int heights[3] = {gridHeight, homeHeight, SHELF_THUMB_HEIGHT};

  for (const int h : heights) {
    if (h <= 0) continue;
    const std::string thumbPath = book.getThumbBmpPath(h);
    if (thumbHeightValid(thumbPath, h)) continue;
    Storage.remove(thumbPath.c_str());  // stale aspect-fill thumb (see thumbHeightValid); rebuild
    if (!book.generateThumbBmp(h, shouldCancel, cancelCtx)) return "";
  }
  return book.getThumbBmpPath();
}
}  // namespace

bool RecentBooksActivity::thumbGenShouldCancel(void* ctx) {
  auto* self = static_cast<RecentBooksActivity*>(ctx);
  if (!self) return false;
  // Yield to a render in flight as well as to a button: rendering runs on its own task and
  // every cover it reads goes through the same SD mutex this conversion is hammering, so a
  // frame that would take 13ms stretched to 30s while a thumbnail was being built.
  if (RenderLock::peek()) return true;
  if (self->mappedInput.anyButtonDownRaw()) {
    // Mark the reader as active from the RAW pin state: the debounced edge is what gets lost
    // while a conversion blocks the loop, so keying the budget below off the DETECTED press
    // would only arm it once a press had already survived -- the very thing that fails here.
    self->lastInputMs = millis();
    return true;
  }

  // Time budget: buttons are only sampled between loop() ticks, so a conversion that runs to
  // completion swallows every click made during it, and the poll above only catches a button
  // that is down at that instant -- not a short press that came and went. Cap a slice while the
  // reader is navigating; once they have been idle for a few seconds, let it run to the end.
  const uint32_t now = millis();
  if (now - self->lastInputMs > THUMB_IDLE_MS) return false;
  return self->thumbGenStartedMs != 0 && now - self->thumbGenStartedMs > self->thumbGenBudgetMs;
}

int RecentBooksActivity::getCellHeight(int cellWidth) const {
  int coverWidth = cellWidth - 2 * COVER_PADDING;
  int coverHeight = coverWidth * COVER_ASPECT_DEN / COVER_ASPECT_NUM;
  int lineHeight = renderer.getLineHeight(SMALL_FONT_ID);
  return COVER_PADDING + coverHeight + CELL_TEXT_GAP + lineHeight + COVER_PADDING;
}

int RecentBooksActivity::getVisibleRows(int cellHeight, int contentHeight) const {
  if (cellHeight <= 0) return 1;
  // Rows are separated by GRID_ROW_GAP: N full rows need N*cellHeight + (N-1)*gap.
  return std::max(1, (contentHeight + GRID_ROW_GAP) / (cellHeight + GRID_ROW_GAP));
}

int RecentBooksActivity::getContentItemCount() const {
  if (selectedTab == 0) return static_cast<int>(recentBooks.size());
  return static_cast<int>(shelves.size());
}

namespace {
constexpr const char* LIBRARY_CACHE_JSON = "/.crosspoint/library_cache.json";
}  // namespace

void RecentBooksActivity::loadRecentBooks() {
  lastRendered.valid = false;  // content changing under the frame -> next render must be full
  // Recents first (most recently opened first), then the persisted result of the last card
  // scan -- instantly, without touching the card tree. A background re-scan (see
  // startLibraryScan) refreshes and re-persists the list afterwards.
  std::vector<RecentBook> recents = RECENT_BOOKS.getBooks();

  {
    RecentBooksStore cache;
    if (cache.loadFromPath(LIBRARY_CACHE_JSON)) {
      // Reuse the cache store's vector allocation. Copying up to 2048 strings into a second
      // vector during a Library click creates a large transient heap spike on the X3.
      std::vector<RecentBook> cached = cache.takeBooks();
      for (auto& recent : recents) {
        const auto known =
            std::find_if(cached.begin(), cached.end(), [&recent](const auto& b) { return b.path == recent.path; });
        if (known == cached.end()) continue;
        if (recent.title.empty()) recent.title = known->title;
        if (recent.author.empty()) recent.author = known->author;
        if (recent.coverBmpPath.empty()) recent.coverBmpPath = known->coverBmpPath;
        cached.erase(known);
      }
      cached.insert(cached.begin(), std::make_move_iterator(recents.begin()), std::make_move_iterator(recents.end()));
      recentBooks = std::move(cached);
      return;
    }
  }
  recentBooks = std::move(recents);
}

namespace {
constexpr char LIBRARY_INDEX_PATH[] = "/.crosspoint/library.idx";
constexpr uint32_t LIBRARY_INDEX_MAGIC = 0x4C494258;  // "LIBX"
constexpr uint8_t LIBRARY_INDEX_VERSION = 3;
constexpr size_t LIBRARY_INDEX_MAX_ENTRIES = 2048;  // guards a corrupt count against the heap
}  // namespace

void RecentBooksActivity::loadLibraryIndex() {
  libraryIndex_.clear();
  libraryIndexDirty_ = false;

  HalFile f;
  if (!Storage.openFileForRead("LIB", LIBRARY_INDEX_PATH, f)) return;
  uint32_t magic = 0;
  uint8_t version = 0;
  uint32_t count = 0;
  if (f.read(&magic, sizeof(magic)) != sizeof(magic) || magic != LIBRARY_INDEX_MAGIC) return;
  if (f.read(&version, sizeof(version)) != sizeof(version) || version != LIBRARY_INDEX_VERSION) return;
  if (f.read(&count, sizeof(count)) != sizeof(count) || count > LIBRARY_INDEX_MAX_ENTRIES) return;

  libraryIndex_.reserve(count);
  for (uint32_t i = 0; i < count; i++) {
    LibraryIndexEntry e;
    if (f.read(&e, sizeof(e)) != sizeof(e)) {
      libraryIndex_.clear();  // truncated file: treat the whole index as absent
      return;
    }
    libraryIndex_.push_back(e);
  }
  LOG_DBG("LIB", "Library index: %u entries", (unsigned)libraryIndex_.size());
}

void RecentBooksActivity::saveLibraryIndex() {
  if (!libraryIndexDirty_) return;
  HalFile f;
  if (!Storage.openFileForWrite("LIB", LIBRARY_INDEX_PATH, f)) return;
  const uint32_t magic = LIBRARY_INDEX_MAGIC;
  const uint8_t version = LIBRARY_INDEX_VERSION;
  const uint32_t count = static_cast<uint32_t>(libraryIndex_.size());
  f.write(&magic, sizeof(magic));
  f.write(&version, sizeof(version));
  f.write(&count, sizeof(count));
  for (const auto& e : libraryIndex_) f.write(&e, sizeof(e));
  f.close();
  libraryIndexDirty_ = false;
}

const RecentBooksActivity::LibraryIndexEntry* RecentBooksActivity::findIndexEntry(const uint32_t pathHash) const {
  const auto it = std::find_if(libraryIndex_.begin(), libraryIndex_.end(),
                               [pathHash](const LibraryIndexEntry& e) { return e.pathHash == pathHash; });
  return it != libraryIndex_.end() ? &*it : nullptr;
}

void RecentBooksActivity::recordIndexEntry(const std::string& path, const uint32_t fileSize,
                                           const uint32_t modifiedStamp, const int thumbHeight, const bool hasThumb) {
  const uint32_t hash = static_cast<uint32_t>(std::hash<std::string>{}(path));
  LibraryIndexEntry entry;
  entry.pathHash = hash;
  entry.fileSize = fileSize;
  entry.modifiedStamp = modifiedStamp;
  entry.thumbHeight = static_cast<uint16_t>(thumbHeight);
  entry.flags = hasThumb ? INDEX_FLAG_HAS_THUMB : 0;

  for (auto& e : libraryIndex_) {
    if (e.pathHash != hash) continue;
    if (e.fileSize == entry.fileSize && e.modifiedStamp == entry.modifiedStamp && e.thumbHeight == entry.thumbHeight &&
        e.flags == entry.flags) {
      return;  // unchanged; no rewrite
    }
    e = entry;
    libraryIndexDirty_ = true;
    return;
  }
  if (libraryIndex_.size() >= LIBRARY_INDEX_MAX_ENTRIES) return;
  libraryIndex_.push_back(entry);
  libraryIndexDirty_ = true;
}

void RecentBooksActivity::startLibraryScan() {
  loadLibraryIndex();
  scan_ = LibraryScanState{};
  scan_.active = true;
  scan_.dirStack.reserve(16);
  scan_.dirStack.push_back("/");
}

bool RecentBooksActivity::stepLibraryScan() {
  if (!scan_.active) return false;

  if (!scan_.walkDone) {
    if (!scan_.activeDir && scan_.dirStack.empty()) {
      scan_.walkDone = true;
      return false;
    }
    scanDirectorySlice();
    return false;
  }

  // EPUB/XTC cover-thumb pass, one book per slice.
  const auto& metrics = UITheme::getInstance().getMetrics();
  const int thumbH =
      gridCoverHeight_ > 0 ? gridCoverHeight_ : (metrics.homeCoverHeight > 0 ? metrics.homeCoverHeight : 120);
  while (scan_.thumbIndex < scan_.results.size()) {
    RecentBook& book = scan_.results[scan_.thumbIndex];
    // A [HEIGHT]-templated path does NOT mean the thumb exists at the height this theme asks
    // for: switching themes changes homeCoverHeight, and skipping on "has a cover path" left
    // every EPUB in the Library without a cover until it was opened again (device report:
    // covers gone after switching to RoundedRaff). The manga pass already re-checks the
    // height; the lookup below does the same here, so only raw (non-templated) paths skip.
    const bool coverIsTemplate = book.coverBmpPath.find("[HEIGHT]") != std::string::npos;
    // .bmp counts too: pages that are already bitmaps still need a thumbnail, because drawing a
    // full-size dithered page into the cell comes out near-black (see BmpToBmpConverter). The
    // book-type gate matters now that .bmp is included -- an EPUB may carry a raw cover.bmp from
    // an older build and must not be treated as a manga folder.
    const bool isMangaEntry = !FsHelpers::hasEpubExtension(book.path) && !FsHelpers::hasXtcExtension(book.path);
    const bool coverIsRawImage =
        isMangaEntry && !book.coverBmpPath.empty() && !coverIsTemplate &&
        (FsHelpers::hasJpgExtension(book.coverBmpPath) || FsHelpers::hasPngExtension(book.coverBmpPath) ||
         FsHelpers::hasBmpExtension(book.coverBmpPath));
    // A manga templated by an EARLIER scan has to come back through here, and used to be skipped
    // for good: this branch only accepted raw paths, and the EPUB check below drops every
    // non-.epub entry. So the heights that scan happened to generate were the only ones a manga
    // ever got. Nothing else fills the gap -- HomeActivity::loadRecentCovers regenerates .epub
    // and .xtc thumbs only -- so the home card resolved its own height against a file nobody
    // would ever write (device log: "[LIB] File does not exist: .../manga_*/thumb_300.bmp").
    // Only the X4 hid it, by falling back to a live raw-JPEG decode; the X3's tighter heap
    // (52272-byte framebuffer, wider viewport) has nothing left for a 20KB JPEGDEC, which is why
    // manga covers were missing there and not here.
    const bool coverIsMangaTemplate = coverIsTemplate && book.coverBmpPath.rfind("/.crosspoint/manga_", 0) == 0;
    const bool mangaThumbMissing =
        coverIsMangaTemplate &&
        (!thumbHeightValid(UITheme::getCoverThumbPath(book.coverBmpPath, thumbH), thumbH) ||
         (metrics.homeCoverHeight > 0 &&
          !thumbHeightValid(UITheme::getCoverThumbPath(book.coverBmpPath, metrics.homeCoverHeight),
                            metrics.homeCoverHeight)));
    // Manga: the walk only recorded the raw page image; convert it here, where the pass is
    // idle-gated and cancellable, instead of freezing the walk.
    if (coverIsRawImage || mangaThumbMissing) {
      if (auto* fcm = renderer.getFontCacheManager()) fcm->releaseAllFontMemory();
      thumbGenStartedMs = millis();
      const std::string thumb =
          ensureMangaCoverThumb(book.path, thumbH, metrics.homeCoverHeight, &thumbGenShouldCancel, this);
      // A cover too big for the current budget would restart forever; give each retry more
      // room. Reset once one completes, so the next book starts responsive again.
      thumbGenBudgetMs = thumb.empty() ? std::min<uint32_t>(thumbGenBudgetMs * 2, 3000) : 400;
      if (!thumb.empty()) {
        book.coverBmpPath = thumb;
        RECENT_BOOKS.updateBook(book.path, book.title, book.author, book.coverBmpPath);
        {
          // Scoped: requestUpdate() must NOT run while the render lock is held (the EPUB branch
          // below does the same), or the update request blocks against the lock this very step
          // is holding.
          RenderLock lock;
          const auto live = std::find_if(recentBooks.begin(), recentBooks.end(),
                                         [&book](const auto& r) { return r.path == book.path; });
          if (live != recentBooks.end()) {
            live->coverBmpPath = book.coverBmpPath;
            lastRendered.valid = false;
          }
        }
        requestUpdate();
      }
      scan_.thumbIndex++;
      return false;  // heavy step: one per slice
    }
    const bool isEpub = FsHelpers::hasEpubExtension(book.path);
    const bool isXtc = FsHelpers::hasXtcExtension(book.path);
    if ((!book.coverBmpPath.empty() && !coverIsTemplate) || (!isEpub && !isXtc)) {
      scan_.thumbIndex++;
      continue;
    }
    std::string cachePath = std::string("/.crosspoint/") + (isEpub ? "epub_" : "xtc_") +
                            std::to_string(std::hash<std::string>{}(book.path));
    std::string thumbPath = cachePath + "/thumb_" + std::to_string(thumbH) + ".bmp";

    // Index shortcut: a record whose size, modification stamp and cover height all still match
    // was verified by an earlier scan, so skip the file open entirely. Only books the index
    // does not vouch for pay for thumbHeightValid() -- that per-book open on every Library
    // visit is what made this pass expensive on a full card.
    uint32_t bookSize = 0, bookStamp = 0;
    {
      HalFile bf;
      if (Storage.openFileForRead("LIB", book.path, bf)) {
        bookSize = static_cast<uint32_t>(bf.size());
        bookStamp = bf.modifiedStamp();
      }
    }
    const uint32_t bookHash = static_cast<uint32_t>(std::hash<std::string>{}(book.path));
    const LibraryIndexEntry* indexed = findIndexEntry(bookHash);
    // The index knows a thumb WAS produced; it cannot know the file is still there. Trusting the
    // flag alone left three books on a test card with a cover the grid could never draw
    // (idxOk=1, file absent) -- and because the shortcut below re-records its own claim, that
    // state sustained itself across every later scan. Confirm with a bare exists(), which still
    // skips the expensive part this shortcut exists for: the header parse and payload-length
    // check inside thumbHeightValid().
    const bool indexSaysThumbOk = indexed && (indexed->flags & INDEX_FLAG_HAS_THUMB) && indexed->fileSize == bookSize &&
                                  indexed->modifiedStamp == bookStamp &&
                                  indexed->thumbHeight == static_cast<uint16_t>(thumbH) &&
                                  Storage.exists(thumbPath.c_str());
    // Height-checked, not just present: earlier builds bounded the thumb's WIDTH too, so a
    // wide cover produced a file that is shorter than its name claims and the grid drew it
    // with a white strip below. thumbHeightValid() sends those through the generator again.
    if (indexSaysThumbOk || thumbHeightValid(thumbPath, thumbH)) {
      book.coverBmpPath = cachePath + "/thumb_[HEIGHT].bmp";
      recordIndexEntry(book.path, bookSize, bookStamp, thumbH, true);
      scan_.thumbIndex++;
      continue;
    }
    // Coalesce the heap first: the cover decode needs a ~20KB contiguous block for the JPEG
    // decoder plus its MCU buffer, and on the X3 (larger viewport, larger font caches) the
    // largest free block can fall below that -- the decode then stops midway and produced a
    // streaked, half-black thumbnail (user report). Fonts reload lazily afterwards. Same step
    // the home screen already takes before generating XTC thumbs.
    if (auto* fcm = renderer.getFontCacheManager()) fcm->releaseAllFontMemory();
    Storage.remove(thumbPath.c_str());  // validated stale above; generators otherwise return early
    thumbGenStartedMs = millis();
    bool generated = false;
    std::string title;
    if (isEpub) {
      Epub epub(book.path, "/.crosspoint");
      // Always skip CSS here: a cover thumbnail never depends on styles, and parsing a
      // publisher stylesheet set costs tens of seconds on an uncached book (observed: 65s
      // loop block on a 6-file Kodansha EPUB). Warming the CSS cache for the reader must
      // not ride on this pass.
      generated = epub.load(true, true) && epub.generateThumbBmp(thumbH, &thumbGenShouldCancel, this);
      title = epub.getTitle();
    } else {
      Xtc xtc(book.path, "/.crosspoint");
      generated = xtc.load() && xtc.generateThumbBmp(thumbH);
      title = xtc.getTitle();
    }
    thumbGenBudgetMs = generated ? 400 : std::min<uint32_t>(thumbGenBudgetMs * 2, 3000);
    recordIndexEntry(book.path, bookSize, bookStamp, thumbH, generated);
    if (generated) {
      book.coverBmpPath = cachePath + "/thumb_[HEIGHT].bmp";
      if (!title.empty()) book.title = title;
      // Surface the new cover immediately (the list was already applied after the walk).
      {
        RenderLock lock;
        const auto live = std::find_if(recentBooks.begin(), recentBooks.end(),
                                       [&book](const auto& r) { return r.path == book.path; });
        if (live != recentBooks.end()) {
          live->coverBmpPath = book.coverBmpPath;
          if (!title.empty()) live->title = book.title;
          lastRendered.valid = false;
        }
      }
      requestUpdate();
    }
    scan_.thumbIndex++;
    return false;  // thumb generation is the heavy step: one per slice
  }

  scan_.active = false;
  return true;
}

void RecentBooksActivity::scanDirectorySlice() {
  // An SD directory entry can cost ~85ms in a large FAT directory. Limiting a tick to two
  // entries keeps input polling moving even when a manga folder contains thousands of files.
  constexpr size_t ENTRIES_PER_SLICE = 2;

  if (!scan_.activeDir) {
    scan_.activeDirPath = std::move(scan_.dirStack.back());
    scan_.dirStack.pop_back();
    scan_.activeDir = Storage.open(scan_.activeDirPath.c_str());
    if (!scan_.activeDir || !scan_.activeDir.isDirectory()) {
      scan_.activeDir = HalFile{};
      scan_.activeDirPath.clear();
      return;
    }
    scan_.activeDir.rewindDirectory();
  }

  size_t entriesRead = 0;
  while (entriesRead < ENTRIES_PER_SLICE) {
    auto f = scan_.activeDir.openNextFile();
    if (!f) {
      scan_.activeDir.close();
      scan_.activeDir = HalFile{};
      scan_.activeDirPath.clear();
      return;
    }
    entriesRead++;
    f.getName(scan_.nameBuf.data(), scan_.nameBuf.size());
    const char* name = scan_.nameBuf.data();
    if (name[0] == '.') continue;
    if (strcmp(name, "System Volume Information") == 0) continue;
    if (strcmp(name, "dict") == 0) continue;

    std::string fullPath = scan_.activeDirPath;
    if (fullPath.back() != '/') fullPath += '/';
    fullPath += name;

    if (f.isDirectory()) {
      const std::string idxPath = fullPath + "/panels.idx";
      if (!Storage.exists(idxPath.c_str())) {
        // Not a manga folder -- descend to find books/manga nested deeper.
        scan_.dirStack.push_back(std::move(fullPath));
        continue;
      }

      // Manga folder: seed from the current list (recents/cache) so stored covers are honored.
      RecentBook entry;
      entry.path = fullPath;
      entry.title = std::string(name);
      const auto cached = std::find_if(recentBooks.begin(), recentBooks.end(),
                                       [&fullPath](const auto& r) { return r.path == fullPath; });
      if (cached != recentBooks.end()) entry = *cached;

      const bool coverIsTemplate = entry.coverBmpPath.find("[HEIGHT]") != std::string::npos;
      const bool coverIsRawImage =
          !entry.coverBmpPath.empty() && !coverIsTemplate &&
          (FsHelpers::hasJpgExtension(entry.coverBmpPath) || FsHelpers::hasPngExtension(entry.coverBmpPath));
      const std::string tmpl = manga::MangaBook(fullPath).getThumbBmpPath();
      const auto& metrics = UITheme::getInstance().getMetrics();
      const int gridHeight =
          gridCoverHeight_ > 0 ? gridCoverHeight_ : (metrics.homeCoverHeight > 0 ? metrics.homeCoverHeight : 120);
      // A manga folder is stamped by its panels.idx: it is rewritten whenever the pages change,
      // and reading it is one open instead of listing hundreds of page files. An index record
      // that still matches means the recorded cover is good, so neither the thumbnail check nor
      // the folder listing below has to run again.
      uint32_t mangaSize = 0, mangaStamp = 0;
      {
        HalFile idxFile;
        if (Storage.openFileForRead("LIB", idxPath, idxFile)) {
          mangaSize = static_cast<uint32_t>(idxFile.size());
          mangaStamp = idxFile.modifiedStamp();
        }
      }
      const uint32_t mangaHash = static_cast<uint32_t>(std::hash<std::string>{}(fullPath));
      const LibraryIndexEntry* mangaIndexed = findIndexEntry(mangaHash);
      const bool indexSaysThumbOk = mangaIndexed && (mangaIndexed->flags & INDEX_FLAG_HAS_THUMB) &&
                                    mangaIndexed->fileSize == mangaSize && mangaIndexed->modifiedStamp == mangaStamp &&
                                    mangaIndexed->thumbHeight == static_cast<uint16_t>(gridHeight);
      const bool thumbOk =
          indexSaysThumbOk || thumbHeightValid(UITheme::getCoverThumbPath(tmpl, gridHeight), gridHeight);
      recordIndexEntry(fullPath, mangaSize, mangaStamp, gridHeight, thumbOk);
      if (entry.coverBmpPath.empty() || coverIsRawImage || (coverIsTemplate && !thumbOk)) {
        const std::string coverBefore = entry.coverBmpPath;
        if (thumbOk) {
          entry.coverBmpPath = tmpl;
        } else if (coverIsRawImage) {
          // Leave the raw page image in place: converting it here would run on the WALK phase,
          // which ticks every loop() with no idle gate, so the whole Library froze while covers
          // were built (device report: no button did anything). The thumb pass below converts
          // it once the reader is idle, and can be cancelled.
        } else {
          // Raw page path only -- see the note above; the idle thumb pass converts it.
          const std::string cover = manga::MangaBook::findCoverImage(fullPath);
          if (!cover.empty()) entry.coverBmpPath = cover;
        }
        // Persist a raw-image -> cached-thumb upgrade so the Home screen also benefits.
        if (coverIsRawImage && entry.coverBmpPath != coverBefore) {
          RECENT_BOOKS.updateBook(entry.path, entry.title, entry.author, entry.coverBmpPath);
        }
      }
      scan_.results.push_back(std::move(entry));
      continue;
    }

    std::string_view fn{name};
    if (!FsHelpers::hasEpubExtension(fn) && !FsHelpers::hasXtcExtension(fn) && !FsHelpers::hasTxtExtension(fn) &&
        !FsHelpers::hasMarkdownExtension(fn))
      continue;
    if (isCrashReportFile(name)) continue;

    RecentBook book;
    book.path = fullPath;
    auto dot = fn.find_last_of('.');
    book.title = std::string(dot != std::string_view::npos ? fn.substr(0, dot) : fn);
    // Seed title/author/cover from the current list so cached metadata survives the re-scan.
    const auto cached =
        std::find_if(recentBooks.begin(), recentBooks.end(), [&fullPath](const auto& r) { return r.path == fullPath; });
    if (cached != recentBooks.end()) book = *cached;
    scan_.results.push_back(std::move(book));
  }
}

void RecentBooksActivity::applyLibraryScan() {
  // Rebuild the list as recents + this pass's results: cached entries whose files vanished
  // drop out, covers repaired by the scan take effect, and the cache is re-persisted.
  std::vector<RecentBook> fresh = RECENT_BOOKS.getBooks();
  for (const auto& r : scan_.results) {
    const auto existing = std::find_if(fresh.begin(), fresh.end(), [&r](const auto& e) { return e.path == r.path; });
    if (existing != fresh.end()) {
      if (!r.coverBmpPath.empty()) existing->coverBmpPath = r.coverBmpPath;
    } else {
      fresh.push_back(r);
    }
  }

  bool changed = fresh.size() != recentBooks.size();
  if (!changed) {
    for (size_t i = 0; i < fresh.size(); i++) {
      if (fresh[i].path != recentBooks[i].path || fresh[i].coverBmpPath != recentBooks[i].coverBmpPath) {
        changed = true;
        break;
      }
    }
  }

  if (changed) {
    {
      RenderLock lock;  // the render task reads these lists concurrently
      recentBooks = std::move(fresh);
      markAllProgressPending();
      if (shelvesLoaded) loadShelves();
      lastRendered.valid = false;
      LOG_DBG("RBA", "Library scan applied: %u books", static_cast<unsigned>(recentBooks.size()));
    }
    // Request outside the RenderLock scope; scan_.results stays alive either way: the idle-time
    // thumb pass still iterates it, and the cache is persisted in finishLibraryScan().
    requestUpdate();
  }
}

void RecentBooksActivity::finishLibraryScan() {
  saveLibraryIndex();
  RecentBooksStore cache;
  cache.setBooks(scan_.results);
  cache.saveToPath(LIBRARY_CACHE_JSON);
  scan_.results.clear();
  scan_.results.shrink_to_fit();
}

void RecentBooksActivity::loadBookProgress() {
  // Progress is filled progressively from loop() -- ~5 file reads per book made the old
  // upfront pass a visible chunk of the Library open time.
  markAllProgressPending();
}

void RecentBooksActivity::markAllProgressPending() {
  bookProgress.clear();
  BookProgress pending;
  pending.percent = PROGRESS_PENDING;
  bookProgress.resize(recentBooks.size(), pending);
}

bool RecentBooksActivity::fillPendingProgress(const int maxCount) {
  int filled = 0;
  bool anyPending = false;
  for (size_t i = 0; i < bookProgress.size() && i < recentBooks.size(); i++) {
    if (bookProgress[i].percent != PROGRESS_PENDING) continue;
    if (filled >= maxCount) {
      anyPending = true;
      break;
    }
    bookProgress[i].percent = readProgressPercent(recentBooks[i].path);
    filled++;
  }
  // No requestUpdate: the visible page's entries are filled synchronously at render time
  // (fillPageProgressNow), so a refresh here would redraw an unchanged screen -- the second
  // full e-ink refresh right after opening was a visible part of the "slow open" feel.
  return anyPending || filled > 0;
}

void RecentBooksActivity::loadShelves() {
  shelvesLoaded = true;
  shelves.clear();

  for (const auto& book : recentBooks) {
    std::string folder = FsHelpers::extractFolderPath(book.path);
    size_t lastSlash = folder.find_last_of('/');
    std::string name =
        (lastSlash != std::string::npos && lastSlash < folder.size() - 1) ? folder.substr(lastSlash + 1) : folder;
    if (folder == "/") name = "Unsorted";

    const auto shelf =
        std::find_if(shelves.begin(), shelves.end(), [&folder](const auto& s) { return s.folderPath == folder; });
    if (shelf != shelves.end()) {
      if (shelf->coverBmpPath.empty() && !book.coverBmpPath.empty()) {
        shelf->coverBmpPath = book.coverBmpPath;
        shelf->coverBookPath = book.path;
      }
    } else {
      ShelfInfo fresh;
      fresh.folderPath = folder;
      fresh.folderName = name;
      fresh.coverBmpPath = book.coverBmpPath;
      if (!book.coverBmpPath.empty()) fresh.coverBookPath = book.path;
      fresh.bookCount = 0;
      shelves.push_back(std::move(fresh));
    }
  }

  constexpr size_t COUNT_BUF_SIZE = 200;
  char countBuf[COUNT_BUF_SIZE];
  for (auto& shelf : shelves) {
    auto root = Storage.open(shelf.folderPath.c_str());
    if (!root || !root.isDirectory()) continue;
    root.rewindDirectory();
    int count = 0;
    for (auto file = root.openNextFile(); file; file = root.openNextFile()) {
      file.getName(countBuf, COUNT_BUF_SIZE);
      if (countBuf[0] == '.') continue;
      if (file.isDirectory()) {
        // Count manga folders (containing panels.idx)
        std::string subDir = shelf.folderPath;
        if (subDir.back() != '/') subDir += '/';
        subDir += countBuf;
        std::string idxCheck = subDir + "/panels.idx";
        if (Storage.exists(idxCheck.c_str())) count++;
        continue;
      }
      std::string_view fn{countBuf};
      if (isCrashReportFile(countBuf)) continue;
      if (FsHelpers::hasEpubExtension(fn) || FsHelpers::hasXtcExtension(fn) || FsHelpers::hasTxtExtension(fn)) {
        count++;
      }
    }
    root.close();
    shelf.bookCount = count;
  }

  std::sort(shelves.begin(), shelves.end(),
            [](const ShelfInfo& a, const ShelfInfo& b) { return a.folderName < b.folderName; });

  // Resolve a shelf-height thumbnail for each shelf's cover so it renders 1:1
  // (the bitmap downscaler produces all-black at heavy reductions).
  for (auto& shelf : shelves) {
    // Any [HEIGHT]-templated cover (EPUB or manga) may already have its 54px variant on SD --
    // resolve it with a pure existence check. Constructing and load()ing an Epub per shelf just
    // to have generateThumbBmp() discover the file exists cost several hundred ms PER SHELF on
    // every Library open (measured as the bulk of an 11s open, together with one first-time
    // thumb generation).
    if (!shelf.coverBmpPath.empty() && shelf.coverBmpPath.find("[HEIGHT]") != std::string::npos) {
      const std::string p = UITheme::getCoverThumbPath(shelf.coverBmpPath, SHELF_THUMB_HEIGHT);
      if (Storage.exists(p.c_str())) {
        shelf.shelfThumbPath = p;
        continue;
      }
    }
    if (shelf.coverBookPath.empty() || !FsHelpers::hasEpubExtension(shelf.coverBookPath)) continue;
    Epub epub(shelf.coverBookPath, "/.crosspoint");
    if (epub.load(true, true) && epub.generateThumbBmp(SHELF_THUMB_HEIGHT)) {
      shelf.shelfThumbPath = epub.getThumbBmpPath(SHELF_THUMB_HEIGHT);
    }
  }
}

void RecentBooksActivity::loadShelfBooks(const std::string& folderPath) {
  lastRendered.valid = false;  // content changing under the frame -> next render must be full
  shelfBooks.clear();
  shelfBookProgress.clear();

  constexpr size_t NAME_BUF_SIZE = 500;
  auto nameBuffer = makeUniqueNoThrow<char[]>(NAME_BUF_SIZE);
  if (!nameBuffer) {
    LOG_ERR("LIB", "OOM: name buffer");
    return;
  }

  auto root = Storage.open(folderPath.c_str());
  if (!root || !root.isDirectory()) return;
  root.rewindDirectory();

  for (auto file = root.openNextFile(); file; file = root.openNextFile()) {
    file.getName(nameBuffer.get(), NAME_BUF_SIZE);
    if (nameBuffer[0] == '.') continue;

    std::string fullPath =
        folderPath == "/" ? "/" + std::string(nameBuffer.get()) : folderPath + "/" + std::string(nameBuffer.get());

    if (file.isDirectory()) {
      // Manga folders (containing panels.idx) count as books within a shelf.
      std::string idxPath = fullPath + "/panels.idx";
      if (!Storage.exists(idxPath.c_str())) continue;

      ShelfBook book;
      book.path = fullPath;
      book.title = std::string(nameBuffer.get());

      const auto recent =
          std::find_if(recentBooks.begin(), recentBooks.end(), [&book](const auto& r) { return r.path == book.path; });
      if (recent != recentBooks.end()) {
        if (!recent->title.empty()) book.title = recent->title;
        book.coverBmpPath = recent->coverBmpPath;
      }
      if (book.coverBmpPath.empty()) {
        // A previously generated (valid) thumb short-circuits the folder scan (same as
        // loadRecentBooks).
        const std::string tmpl = manga::MangaBook(fullPath).getThumbBmpPath();
        const auto& metrics = UITheme::getInstance().getMetrics();
        const int gridHeight =
            gridCoverHeight_ > 0 ? gridCoverHeight_ : (metrics.homeCoverHeight > 0 ? metrics.homeCoverHeight : 120);
        if (thumbHeightValid(UITheme::getCoverThumbPath(tmpl, gridHeight), gridHeight)) {
          book.coverBmpPath = tmpl;
        } else {
          const std::string sourcePath = manga::MangaBook::findCoverImage(fullPath);
          if (!sourcePath.empty()) {
            if (auto* fcm = renderer.getFontCacheManager()) fcm->releaseAllFontMemory();
            const std::string thumb =
                ensureMangaCoverThumb(fullPath, gridHeight, metrics.homeCoverHeight, &thumbGenShouldCancel, this);
            book.coverBmpPath = !thumb.empty() ? thumb : sourcePath;
          }
        }
      }

      shelfBooks.push_back(std::move(book));
      continue;
    }

    std::string_view filename{nameBuffer.get()};
    if (!FsHelpers::hasEpubExtension(filename) && !FsHelpers::hasXtcExtension(filename) &&
        !FsHelpers::hasTxtExtension(filename))
      continue;
    if (isCrashReportFile(nameBuffer.get())) continue;

    ShelfBook book;
    book.path = fullPath;

    auto dotPos = filename.find_last_of('.');
    book.title = std::string(dotPos != std::string_view::npos ? filename.substr(0, dotPos) : filename);

    const auto recent =
        std::find_if(recentBooks.begin(), recentBooks.end(), [&book](const auto& r) { return r.path == book.path; });
    if (recent != recentBooks.end()) {
      if (!recent->title.empty()) book.title = recent->title;
      book.coverBmpPath = recent->coverBmpPath;
    }

    if (book.coverBmpPath.empty()) {
      std::string cachePath;
      if (FsHelpers::hasEpubExtension(filename)) {
        cachePath = "/.crosspoint/epub_" + std::to_string(std::hash<std::string>{}(book.path));
      } else if (FsHelpers::hasXtcExtension(filename)) {
        cachePath = "/.crosspoint/xtc_" + std::to_string(std::hash<std::string>{}(book.path));
      }
      if (!cachePath.empty()) {
        const auto& metrics = UITheme::getInstance().getMetrics();
        std::string thumbPath = cachePath + "/thumb_" + std::to_string(metrics.homeCoverHeight) + ".bmp";
        if (Storage.exists(thumbPath.c_str())) {
          book.coverBmpPath = cachePath + "/thumb_[HEIGHT].bmp";
        }
      }
    }

    shelfBooks.push_back(std::move(book));
  }
  root.close();

  std::sort(shelfBooks.begin(), shelfBooks.end(),
            [](const ShelfBook& a, const ShelfBook& b) { return a.title < b.title; });

  shelfBookProgress.reserve(shelfBooks.size());
  for (const auto& book : shelfBooks) {
    BookProgress bp;
    bp.percent = readProgressPercent(book.path);
    shelfBookProgress.push_back(bp);
  }
}

int RecentBooksActivity::readProgressPercent(const std::string& bookPath) const {
  std::string cachePath;
  if (FsHelpers::hasEpubExtension(bookPath)) {
    cachePath = "/.crosspoint/epub_" + std::to_string(std::hash<std::string>{}(bookPath));
  } else if (FsHelpers::hasXtcExtension(bookPath)) {
    return XtcProgress::percentForBook(bookPath);
  } else if (manga::MangaBook::isMangaFolder(bookPath)) {
    std::string mangaCachePath = "/.crosspoint/manga_" + std::to_string(std::hash<std::string>{}(bookPath));
    HalFile f;
    if (!Storage.openFileForRead("LIB", mangaCachePath + "/progress.bin", f)) return 0;
    uint8_t data[4];
    if (f.read(data, 4) != 4) return 0;
    uint32_t currentPage = data[0] | (data[1] << 8) | (data[2] << 16) | (data[3] << 24);
    HalFile idxFile;
    if (!Storage.openFileForRead("LIB", bookPath + "/panels.idx", idxFile)) return 0;
    uint8_t hdr[8];
    if (idxFile.read(hdr, 8) != 8) return 0;
    uint32_t totalPages = hdr[4] | (hdr[5] << 8) | (hdr[6] << 16) | (hdr[7] << 24);
    if (totalPages == 0) return 0;
    int pct = static_cast<int>((static_cast<float>(currentPage) / static_cast<float>(totalPages)) * 100.0f + 0.5f);
    return std::clamp(pct, 0, 100);
  } else {
    return -1;
  }

  if (FsHelpers::hasEpubExtension(bookPath)) {
    const int pct = EpubProgress::percentFromCache(cachePath, "LIB");
    return pct < 0 ? 0 : pct;
  }
  return -1;
}

void RecentBooksActivity::onEnter() {
  Activity::onEnter();
  lastInputMs = millis();

  if (RECENT_BOOKS.pruneMissing()) {
    RECENT_BOOKS.saveToFile();
  }

  loadRecentBooks();
  loadBookProgress();
  shelvesLoaded = false;
  startLibraryScan();

  selectedTab = 0;
  contentIndex = 0;
  scrollRow = 0;
  openShelfIndex = -1;
  requestUpdate();
}

void RecentBooksActivity::onExit() {
  Activity::onExit();
  recentBooks.clear();
  bookProgress.clear();
  shelves.clear();
  shelfBooks.clear();
  shelfBookProgress.clear();
}

void RecentBooksActivity::loop() {
  const int pageItems = UITheme::getInstance().getNumberOfItemsPerPage(renderer, true, false, true, true);
  const auto& metrics = UITheme::getInstance().getMetrics();
  const int contentTop = metrics.topPadding + metrics.headerHeight + metrics.verticalSpacing;
  const int contentHeight =
      renderer.getScreenHeight() - contentTop - metrics.buttonHintsHeight - metrics.verticalSpacing;

  if (openShelfIndex >= 0) {
    if (mappedInput.wasPressed(MappedInputManager::Button::Back)) {
      openShelfIndex = -1;
      shelfBooks.clear();
      shelfBookProgress.clear();
      requestUpdate();
      return;
    }

    if (mappedInput.wasPressed(MappedInputManager::Button::Confirm)) {
      if (shelfContentIndex < static_cast<int>(shelfBooks.size())) {
        LOG_DBG("RBA", "Selected shelf book: %s", shelfBooks[shelfContentIndex].path.c_str());
        onSelectBook(shelfBooks[shelfContentIndex].path);
        return;
      }
    }

    const int shelfItemCount = static_cast<int>(shelfBooks.size());
    if (shelfItemCount > 0) {
      buttonNavigator.onNextRelease([this, shelfItemCount] {
        shelfContentIndex = ButtonNavigator::nextIndex(shelfContentIndex, shelfItemCount);
        requestUpdate();
      });
      buttonNavigator.onPreviousRelease([this, shelfItemCount] {
        shelfContentIndex = ButtonNavigator::previousIndex(shelfContentIndex, shelfItemCount);
        requestUpdate();
      });
    }
    return;
  }

  bool hasChangedTab = false;

  if (mappedInput.wasPressed(MappedInputManager::Button::Confirm)) {
    if (contentIndex == 0) {
      selectedTab = (selectedTab + 1) % TAB_COUNT;
      hasChangedTab = true;
      if (selectedTab == 1 && !shelvesLoaded) loadShelves();
      requestUpdate();
    } else {
      const int itemIdx = contentIndex - 1;
      if (selectedTab == 0) {
        if (itemIdx < static_cast<int>(recentBooks.size())) {
          LOG_DBG("RBA", "Selected recent book: %s", recentBooks[itemIdx].path.c_str());
          onSelectBook(recentBooks[itemIdx].path);
          return;
        }
      } else {
        if (itemIdx < static_cast<int>(shelves.size())) {
          LOG_DBG("RBA", "Opening shelf: %s", shelves[itemIdx].folderPath.c_str());
          openShelfIndex = itemIdx;
          shelfContentIndex = 0;
          shelfScrollRow = 0;
          loadShelfBooks(shelves[itemIdx].folderPath);
          requestUpdate();
          return;
        }
      }
    }
  }

  if (longPressFired) {
    if (!mappedInput.isPressed(MappedInputManager::Button::Confirm)) {
      longPressFired = false;
    }
    return;
  }

  if (selectedTab == 0 && contentIndex > 0) {
    const int itemIdx = contentIndex - 1;
    if (itemIdx < static_cast<int>(recentBooks.size()) && mappedInput.isPressed(MappedInputManager::Button::Confirm) &&
        mappedInput.getHeldTime() >= LONG_PRESS_MS) {
      longPressFired = true;
      promptRemoveBook(recentBooks[itemIdx].path, recentBooks[itemIdx].title);
      return;
    }
  }

  // Upstream's flat recents list (selectorIndex + handleListTouch) doesn't exist here: this
  // screen is a tabbed cover GRID addressed by contentIndex/scrollRow. Swipes move one grid
  // row; Back stays with the tab/shelf-aware handler below rather than always going home.
  const auto swipe = mappedInput.wasSwipe();
  if (swipe == MappedInputManager::SwipeDir::Up || swipe == MappedInputManager::SwipeDir::Down) {
    const int totalItems = getContentItemCount() + 1;
    const int delta = (swipe == MappedInputManager::SwipeDir::Up) ? GRID_COLS : -GRID_COLS;
    const int moved = std::clamp(contentIndex + delta, 0, std::max(0, totalItems - 1));
    if (moved != contentIndex) {
      contentIndex = moved;
      requestUpdate();
    }
    return;
  }

  if (mappedInput.wasPressed(MappedInputManager::Button::Back)) {
    if (contentIndex > 0) {
      contentIndex = 0;
      scrollRow = 0;
      requestUpdate();
    } else {
      onGoHome();
    }
    return;
  }

  const int totalItems = getContentItemCount() + 1;

  buttonNavigator.onNextRelease([this, totalItems] {
    contentIndex = ButtonNavigator::nextIndex(contentIndex, totalItems);
    requestUpdate();
  });

  buttonNavigator.onPreviousRelease([this, totalItems] {
    contentIndex = ButtonNavigator::previousIndex(contentIndex, totalItems);
    requestUpdate();
  });

  buttonNavigator.onNextContinuous([this, &hasChangedTab] {
    hasChangedTab = true;
    selectedTab = ButtonNavigator::nextIndex(selectedTab, TAB_COUNT);
    requestUpdate();
  });

  buttonNavigator.onPreviousContinuous([this, &hasChangedTab] {
    hasChangedTab = true;
    selectedTab = ButtonNavigator::previousIndex(selectedTab, TAB_COUNT);
    requestUpdate();
  });

  if (hasChangedTab) {
    contentIndex = (contentIndex == 0) ? 0 : 1;
    scrollRow = 0;
    if (selectedTab == 1 && !shelvesLoaded) loadShelves();
  }

  // Background work, one slice per tick: re-scan the card (stale-while-revalidate) and fill
  // pending progress percentages. Runs after input handling so button latency is unaffected.
  // Walk slices are cheap (one directory listing each) and run every tick; the list is applied
  // the moment the walk completes so a new book appears within a second. The thumb/metadata
  // slices are HEAVY (a new epub costs full metadata indexing + a cover decode, ~2-3s
  // observed) -- they only run while the user is idle so a press never lands mid-slice.
  if (mappedInput.wasAnyPressed()) lastInputMs = millis();
  if (scan_.active) {
    // Both phases are idle-gated now. The walk was assumed cheap ("one directory listing"),
    // but a manga folder holds hundreds of page files and listing one costs seconds on SD
    // (measured: a 2220ms loop gap) -- a click landing inside that window is never even sampled
    // as a press, so the Library felt completely dead while it scanned.
    const uint32_t idleBeforeWorkMs = scan_.walkDone ? THUMB_IDLE_MS : 700;
    if (millis() - lastInputMs > idleBeforeWorkMs && !RenderLock::peek()) {
      const bool wasWalking = !scan_.walkDone;
      const bool done = stepLibraryScan();
      if (wasWalking && scan_.walkDone) applyLibraryScan();  // books show up now; covers follow
      if (done) finishLibraryScan();
    }
  } else {
    fillPendingProgress(3);
  }
}

void RecentBooksActivity::promptRemoveBook(const std::string& path, const std::string& title) {
  auto handler = [this, path](const ActivityResult& res) {
    // The confirmation dialog painted over our frame (whether confirmed or cancelled), so the
    // next render must be a full one -- a partial redraw would leave dialog remnants on screen.
    lastRendered.valid = false;
    if (res.isCancelled) {
      LOG_DBG("RBA", "Remove from recents cancelled");
      return;
    }
    if (RECENT_BOOKS.removeByPath(path)) {
      LOG_DBG("RBA", "Removed from recents: %s", path.c_str());
      loadRecentBooks();
      loadBookProgress();
      if (shelvesLoaded) loadShelves();
      if (recentBooks.empty()) {
        contentIndex = 0;
      } else if (contentIndex - 1 >= static_cast<int>(recentBooks.size())) {
        contentIndex = static_cast<int>(recentBooks.size());
      }
      requestUpdate(true);
    }
  };

  startActivityForResult(
      std::make_unique<ConfirmationActivity>(renderer, mappedInput, tr(STR_REMOVE_FROM_RECENTS), title),
      std::move(handler));
}

void RecentBooksActivity::drawGridSelectionBorder(const int cellX, const int cellY, const int cellWidth,
                                                  const int cellHeight, const bool on) {
  (void)cellHeight;
  const int coverWidth = cellWidth - 2 * COVER_PADDING;
  const int coverHeight = coverWidth * COVER_ASPECT_DEN / COVER_ASPECT_NUM;
  const int coverX = cellX + COVER_PADDING;
  const int coverY = cellY + COVER_PADDING;
  // Two nested 1px rects = a 2px ring at offsets -2/-3 from the cover box: a 1px white gap
  // separates it from the cover's own 1px outline, and it stays clear of the progress label
  // below (labelY = cover bottom + CELL_TEXT_GAP).
  renderer.drawRect(coverX - 2, coverY - 2, coverWidth + 4, coverHeight + 4, on);
  renderer.drawRect(coverX - 3, coverY - 3, coverWidth + 6, coverHeight + 6, on);
}

void RecentBooksActivity::drawGridCell(const int cellX, const int cellY, const int cellWidth, const int cellHeight,
                                       const std::string& coverBmpPath, const std::string& title,
                                       const int progressPercent, const bool selected, const bool drawTitle) {
  const auto& metrics = UITheme::getInstance().getMetrics();
  const int coverWidth = cellWidth - 2 * COVER_PADDING;
  const int coverHeight = coverWidth * COVER_ASPECT_DEN / COVER_ASPECT_NUM;
  // Request the thumb at the size it is drawn at: a theme-sized thumb (300px, 400px in
  // Classic) scaled into this cell cost ~2.5s per cover in software scaling.
  const int thumbHeight = coverHeight;
  gridCoverHeight_ = coverHeight;
  const int lineHeight = renderer.getLineHeight(SMALL_FONT_ID);
  const int coverX = cellX + COVER_PADDING;
  const int coverY = cellY + COVER_PADDING;

  if (selected) {
    drawGridSelectionBorder(cellX, cellY, cellWidth, cellHeight, true);
  }

  bool hasCover = false;
  if (!coverBmpPath.empty()) {
    const std::string coverPath = UITheme::getCoverThumbPath(coverBmpPath, thumbHeight);
    // Shared helper: manga covers are raw page images (JPG/PNG), EPUB/XTC covers pre-cropped
    // BMP thumbnails. Both fill the cell and crop the overflow rather than letterboxing.
    hasCover = UITheme::drawCoverThumbFilled(renderer, coverPath, coverX, coverY, coverWidth, coverHeight,
                                             /*allowRawDecode=*/false);
  }

  renderer.drawRect(coverX, coverY, coverWidth, coverHeight, true);

  if (!hasCover) {
    renderer.drawIcon(CoverIcon, coverX + (coverWidth - 32) / 2, coverY + (coverHeight - 32) / 2, 32);
    auto titleLines = renderer.wrappedText(SMALL_FONT_ID, title.c_str(), coverWidth - 8, 3);
    int textY = coverY + (coverHeight - 32) / 2 + 36;
    for (const auto& line : titleLines) {
      if (textY + lineHeight > coverY + coverHeight) break;
      const int textW = renderer.getTextWidth(SMALL_FONT_ID, line.c_str());
      const int textX = coverX + (coverWidth - textW) / 2;
      renderer.drawText(SMALL_FONT_ID, textX, textY, line.c_str(), true);
      textY += lineHeight;
    }
  }

  // Progress badge on the cover (top-right, white on black): "NEW" for unstarted books,
  // "Read" for finished ones, else the percentage. progressPercent < 0 means the idle-gated
  // progress pass hasn't reached this book yet -- draw nothing rather than a wrong badge.
  if (progressPercent >= 0) {
    char badgeBuf[8];
    if (progressPercent <= 0) {
      snprintf(badgeBuf, sizeof(badgeBuf), "%s", tr(STR_BOOK_BADGE_NEW));
    } else if (progressPercent >= 100) {
      snprintf(badgeBuf, sizeof(badgeBuf), "%s", tr(STR_BOOK_BADGE_READ));
    } else {
      snprintf(badgeBuf, sizeof(badgeBuf), "%d%%", progressPercent);
    }
    const int badgeTextW = renderer.getTextWidth(SMALL_FONT_ID, badgeBuf);
    const int badgeH = renderer.getLineHeight(SMALL_FONT_ID) + 4;
    const int badgeW = badgeTextW + 12;
    const int badgeX = coverX + coverWidth - badgeW;
    const int badgeY = coverY;
    // Black fill with a rounded bottom-left corner; pixels outside the arc stay untouched so
    // the cover shows through the corner notch.
    constexpr int badgeR = 4;
    renderer.fillRect(badgeX + badgeR, badgeY, badgeW - badgeR, badgeH, true);
    renderer.fillRect(badgeX, badgeY, badgeR, badgeH - badgeR, true);
    const int arcCx = badgeX + badgeR;
    const int arcCy = badgeY + badgeH - 1 - badgeR;
    for (int dy = 0; dy <= badgeR; dy++) {
      for (int dx = 0; dx <= badgeR; dx++) {
        const int d2 = dx * dx + dy * dy;
        if (d2 > badgeR * badgeR) continue;
        // Outermost ring of the arc is white so it joins the white edge lines below.
        renderer.drawPixel(arcCx - dx, arcCy + dy, d2 < (badgeR - 1) * (badgeR - 1));
      }
    }
    // White border on the two exposed edges (left + bottom); top/right sit on the cover edge.
    renderer.drawLine(badgeX, badgeY, badgeX, arcCy, false);
    renderer.drawLine(arcCx, badgeY + badgeH - 1, badgeX + badgeW - 1, badgeY + badgeH - 1, false);
    renderer.drawText(SMALL_FONT_ID, badgeX + 6, badgeY + 2, badgeBuf, false);
  }

  // Title below the cover, single line, ellipsis-truncated. The peek row skips this: its
  // title band lies under the button hints, so measuring/truncating it would be wasted work.
  const int labelY = coverY + coverHeight + CELL_TEXT_GAP;
  if (drawTitle && !title.empty()) {
    const std::string line = renderer.truncatedText(SMALL_FONT_ID, title.c_str(), coverWidth);
    renderer.drawText(SMALL_FONT_ID, coverX, labelY, line.c_str(), true);
  }
}

// Read the progress for the visible window's pending entries NOW (bounded: <=9 small reads).
// The deferred background pass still covers everything else; it just never gets to trigger a
// second full-screen refresh for cells the user is currently looking at.
void RecentBooksActivity::fillPageProgressNow(std::vector<BookProgress>& progress, const std::vector<RecentBook>* books,
                                              const std::vector<ShelfBook>* sBooks, const int firstIdx,
                                              const int lastIdx) {
  for (int i = firstIdx; i >= 0 && i <= lastIdx && i < static_cast<int>(progress.size()); i++) {
    if (progress[i].percent != PROGRESS_PENDING) continue;
    const std::string& path = books ? (*books)[i].path : (*sBooks)[i].path;
    progress[i].percent = readProgressPercent(path);
  }
}

void RecentBooksActivity::renderBooksTab(int contentTop, int contentHeight) {
  const auto& metrics = UITheme::getInstance().getMetrics();
  const auto pageWidth = renderer.getScreenWidth();

  if (recentBooks.empty()) {
    renderer.drawText(UI_10_FONT_ID, metrics.contentSidePadding, contentTop + 20, tr(STR_NO_RECENT_BOOKS));
    return;
  }

  const int gridWidth = pageWidth - 2 * metrics.contentSidePadding;
  const int cellWidth = gridWidth / GRID_COLS;
  const int cellHeight = getCellHeight(cellWidth);
  const int rowStride = cellHeight + GRID_ROW_GAP;
  const int visibleRows = getVisibleRows(cellHeight, contentHeight);
  const int bookCount = static_cast<int>(recentBooks.size());
  const int totalRows = (bookCount + GRID_COLS - 1) / GRID_COLS;
  const int selectedItem = contentIndex - 1;

  const int selectedRow = selectedItem >= 0 ? selectedItem / GRID_COLS : 0;
  if (selectedRow < scrollRow) scrollRow = selectedRow;
  if (selectedRow >= scrollRow + visibleRows) scrollRow = selectedRow - visibleRows + 1;

  // One extra row peeks behind the button bar as a "more below" hint (covers and badges show;
  // the hint bar overdraws the bottom). Its titles sit fully under the hints, so they are
  // never drawn or measured.
  const int renderRows = std::min(totalRows - scrollRow, visibleRows + 1);
  const int firstIdx = scrollRow * GRID_COLS;
  const int lastIdx = std::min(firstIdx + renderRows * GRID_COLS, bookCount) - 1;
  const int titledLastIdx = std::min(firstIdx + visibleRows * GRID_COLS, bookCount) - 1;

  // Fill the visible window's progress badges synchronously (max 9 books, ~2 small reads each)
  // so the first paint is already correct -- the deferred background pass caused a SECOND full
  // e-ink refresh right after opening, which read as sluggishness.
  fillPageProgressNow(bookProgress, &recentBooks, nullptr, firstIdx, lastIdx);

  // Prewarm titles for the full rows only (the peek row's titles are never drawn).
  if (renderer.getFontCacheManager()) {
    std::string prewarmBuf;
    prewarmBuf.reserve(256);
    for (int idx = firstIdx; idx <= titledLastIdx; idx++) {
      prewarmBuf += recentBooks[idx].title;
      prewarmBuf += ' ';
    }
    renderer.prewarmText(SMALL_FONT_ID, prewarmBuf.c_str(), 1 << EpdFontFamily::REGULAR);
  }

  for (int idx = firstIdx; idx <= lastIdx; idx++) {
    const int local = idx - firstIdx;
    const int col = local % GRID_COLS;
    const int row = local / GRID_COLS;
    const int cellX = metrics.contentSidePadding + col * cellWidth;
    const int cellY = contentTop + row * rowStride;
    const int pct = idx < static_cast<int>(bookProgress.size()) ? bookProgress[idx].percent : -1;
    drawGridCell(cellX, cellY, cellWidth, cellHeight, recentBooks[idx].coverBmpPath, recentBooks[idx].title, pct,
                 idx == selectedItem, /*drawTitle=*/idx <= titledLastIdx);
  }

  // Release the page slots claimed by the prewarm above -- see the matching comment in
  // LyraTheme::drawRecentBookCover for why this is required (FontDecompressor's page-slot pool
  // is small and shared globally; an unreleased prewarm permanently starves every other screen).
  if (auto* fcm = renderer.getFontCacheManager()) {
    fcm->clearCache();
  }
}

void RecentBooksActivity::drawShelfRow(const int shelfIdx, const int itemY, const bool selected) {
  const auto& metrics = UITheme::getInstance().getMetrics();
  const auto pageWidth = renderer.getScreenWidth();
  const int rowHeight = metrics.listWithSubtitleRowHeight;
  const int chevronMargin = 15;
  const auto& shelf = shelves[shelfIdx];

  if (selected) {
    renderer.fillRoundedRect(metrics.contentSidePadding - 6, itemY - 4, pageWidth - 2 * metrics.contentSidePadding + 12,
                             rowHeight + 8, SELECTION_RADIUS, Color::LightGray);
  }

  int thumbX = metrics.contentSidePadding + 4;
  int thumbY = itemY + (rowHeight - SHELF_THUMB_HEIGHT) / 2;

  bool hasThumb = false;
  // The shelf-height thumbnail (generated in loadShelves) renders 1:1, avoiding
  // the bitmap downscaler that produces all-black at heavy reductions.
  if (!shelf.shelfThumbPath.empty()) {
    HalFile file;
    if (Storage.openFileForRead("LIB", shelf.shelfThumbPath, file)) {
      Bitmap bitmap(file);
      if (bitmap.parseHeaders() == BmpReaderError::Ok) {
        // Center the (already small) thumb in the slot; no scaling needed.
        const int bw = bitmap.getWidth();
        const int bh = bitmap.getHeight();
        const int dx = thumbX + (SHELF_THUMB_WIDTH - bw) / 2;
        const int dy = thumbY + (SHELF_THUMB_HEIGHT - bh) / 2;
        renderer.drawBitmap(bitmap, dx, dy, bw, bh);
        hasThumb = true;
      }
      file.close();
    }
  } else if (!shelf.coverBmpPath.empty() &&
             (FsHelpers::hasJpgExtension(shelf.coverBmpPath) || FsHelpers::hasPngExtension(shelf.coverBmpPath))) {
    // Manga covers are JPG/PNG page images (no pre-rendered shelf thumb) --
    // decode and scale directly into the thumb slot.
    ImageToFramebufferDecoder* decoder = ImageDecoderFactory::getDecoder(shelf.coverBmpPath);
    if (decoder) {
      ImageDimensions dims = {0, 0};
      if (decoder->getDimensions(shelf.coverBmpPath, dims) && dims.width > 0 && dims.height > 0) {
        const int drawW = SHELF_THUMB_HEIGHT * dims.width / dims.height;
        RenderConfig config;
        config.x = thumbX + (SHELF_THUMB_WIDTH - drawW) / 2;
        config.y = thumbY;
        config.maxWidth = drawW;
        config.maxHeight = SHELF_THUMB_HEIGHT;
        config.useGrayscale = false;
        config.useDithering = true;
        if (decoder->decodeToFramebuffer(shelf.coverBmpPath, renderer, config)) {
          hasThumb = true;
        }
      }
    }
  }

  if (!hasThumb) {
    renderer.drawRect(thumbX, thumbY, SHELF_THUMB_WIDTH, SHELF_THUMB_HEIGHT, true);
  }

  const int textX = thumbX + SHELF_THUMB_WIDTH + 12;
  const int smallLH = renderer.getLineHeight(SMALL_FONT_ID);
  const int nameY = itemY + rowHeight / 2 - smallLH;

  renderer.drawText(UI_10_FONT_ID, textX, nameY, shelf.folderName.c_str(), true, EpdFontFamily::BOLD);

  char countBuf[32];
  if (shelf.bookCount == 1) {
    snprintf(countBuf, sizeof(countBuf), "%s", tr(STR_SHELF_BOOK_COUNT_1));
  } else {
    snprintf(countBuf, sizeof(countBuf), tr(STR_SHELF_BOOK_COUNT_N), shelf.bookCount);
  }
  renderer.drawText(SMALL_FONT_ID, textX, nameY + smallLH + 1, countBuf, true);

  const int chevronSize = 6;
  const int chevronX = pageWidth - metrics.contentSidePadding - chevronMargin;
  const int chevronY = itemY + rowHeight / 2;
  renderer.drawLine(chevronX, chevronY - chevronSize, chevronX + chevronSize, chevronY, true);
  renderer.drawLine(chevronX + chevronSize, chevronY, chevronX, chevronY + chevronSize, true);
  renderer.drawLine(chevronX + 1, chevronY - chevronSize, chevronX + chevronSize + 1, chevronY, true);
  renderer.drawLine(chevronX + chevronSize + 1, chevronY, chevronX + 1, chevronY + chevronSize, true);
}

void RecentBooksActivity::renderShelvesTab(int contentTop, int contentHeight) {
  const auto& metrics = UITheme::getInstance().getMetrics();
  const auto pageWidth = renderer.getScreenWidth();

  if (shelves.empty()) {
    renderer.drawText(UI_10_FONT_ID, metrics.contentSidePadding, contentTop + 20, tr(STR_NO_SHELVES));
    return;
  }

  const int rowHeight = metrics.listWithSubtitleRowHeight;
  const int visibleItems = std::max(1, contentHeight / rowHeight);
  const int selectedItem = contentIndex - 1;
  const int shelfCount = static_cast<int>(shelves.size());

  int scrollOffset = 0;
  if (selectedItem >= visibleItems) {
    scrollOffset = selectedItem - visibleItems + 1;
  }

  // Prewarm the font cache with all visible folder names before drawing. Folder names are drawn
  // unconditionally on every render (unlike cover-fallback titles below), so without this, non-Latin
  // names (e.g. Japanese folders) hit FontDecompressor's slow single-slot fallback on every navigation
  // step -- one full ~64KB group decompression per name that lands in a different glyph group.
  if (renderer.getFontCacheManager()) {
    std::string prewarmBuf;
    prewarmBuf.reserve(256);
    for (int i = scrollOffset; i < std::min(scrollOffset + visibleItems, shelfCount); i++) {
      prewarmBuf += shelves[i].folderName;
      prewarmBuf += ' ';
    }
    renderer.prewarmText(UI_10_FONT_ID, prewarmBuf.c_str(), 1 << EpdFontFamily::BOLD);
  }

  for (int i = scrollOffset; i < std::min(scrollOffset + visibleItems, shelfCount); i++) {
    const int itemY = contentTop + (i - scrollOffset) * rowHeight;
    drawShelfRow(i, itemY, i == selectedItem);
  }

  if (shelfCount > visibleItems) {
    const int barX = pageWidth - metrics.scrollBarRightOffset - metrics.scrollBarWidth;
    const int thumbBarH = std::max(10, contentHeight * visibleItems / shelfCount);
    const int thumbBarY = contentTop + (contentHeight - thumbBarH) * scrollOffset / (shelfCount - visibleItems);
    renderer.fillRect(barX, thumbBarY, metrics.scrollBarWidth, thumbBarH, true);
  }

  // Release the page slots claimed by the prewarm above -- see the matching comment in
  // LyraTheme::drawRecentBookCover for why this is required.
  if (auto* fcm = renderer.getFontCacheManager()) {
    fcm->clearCache();
  }
}

void RecentBooksActivity::renderShelfBooksView(int contentTop, int contentHeight) {
  const auto& metrics = UITheme::getInstance().getMetrics();
  const auto pageWidth = renderer.getScreenWidth();

  if (shelfBooks.empty()) {
    renderer.drawText(UI_10_FONT_ID, metrics.contentSidePadding, contentTop + 20, tr(STR_NO_FILES_FOUND));
    return;
  }

  const int gridWidth = pageWidth - 2 * metrics.contentSidePadding;
  const int cellWidth = gridWidth / GRID_COLS;
  const int cellHeight = getCellHeight(cellWidth);
  const int rowStride = cellHeight + GRID_ROW_GAP;
  const int visibleRows = getVisibleRows(cellHeight, contentHeight);
  const int bookCount = static_cast<int>(shelfBooks.size());
  const int totalRows = (bookCount + GRID_COLS - 1) / GRID_COLS;

  const int selectedRow = shelfContentIndex >= 0 ? shelfContentIndex / GRID_COLS : 0;
  if (selectedRow < shelfScrollRow) shelfScrollRow = selectedRow;
  if (selectedRow >= shelfScrollRow + visibleRows) shelfScrollRow = selectedRow - visibleRows + 1;

  // See renderBooksTab: one peek row, no titles on it, badges filled synchronously.
  const int renderRows = std::min(totalRows - shelfScrollRow, visibleRows + 1);
  const int firstIdx = shelfScrollRow * GRID_COLS;
  const int lastIdx = std::min(firstIdx + renderRows * GRID_COLS, bookCount) - 1;
  const int titledLastIdx = std::min(firstIdx + visibleRows * GRID_COLS, bookCount) - 1;

  fillPageProgressNow(shelfBookProgress, nullptr, &shelfBooks, firstIdx, lastIdx);

  if (renderer.getFontCacheManager()) {
    std::string prewarmBuf;
    prewarmBuf.reserve(256);
    for (int idx = firstIdx; idx <= titledLastIdx; idx++) {
      prewarmBuf += shelfBooks[idx].title;
      prewarmBuf += ' ';
    }
    renderer.prewarmText(SMALL_FONT_ID, prewarmBuf.c_str(), 1 << EpdFontFamily::REGULAR);
  }

  for (int idx = firstIdx; idx <= lastIdx; idx++) {
    const int local = idx - firstIdx;
    const int col = local % GRID_COLS;
    const int row = local / GRID_COLS;
    const int cellX = metrics.contentSidePadding + col * cellWidth;
    const int cellY = contentTop + row * rowStride;
    const int pct = idx < static_cast<int>(shelfBookProgress.size()) ? shelfBookProgress[idx].percent : -1;
    drawGridCell(cellX, cellY, cellWidth, cellHeight, shelfBooks[idx].coverBmpPath, shelfBooks[idx].title, pct,
                 idx == shelfContentIndex, /*drawTitle=*/idx <= titledLastIdx);
  }

  // Release the page slots claimed by the prewarm above -- see the matching comment in
  // LyraTheme::drawRecentBookCover for why this is required.
  if (auto* fcm = renderer.getFontCacheManager()) {
    fcm->clearCache();
  }
}

bool RecentBooksActivity::tryPartialSelectionRedraw() {
  if (!lastRendered.valid) return false;
  if (openShelfIndex != lastRendered.openShelf || selectedTab != lastRendered.tab) return false;

  const auto& metrics = UITheme::getInstance().getMetrics();
  const auto pageWidth = renderer.getScreenWidth();
  const auto pageHeight = renderer.getScreenHeight();
  auto* fcm = renderer.getFontCacheManager();

  if (openShelfIndex >= 0) {
    // Shelf-books grid: pure cell-to-cell move within the rendered scroll window.
    const int oldIdx = lastRendered.shelfContentIndex;
    const int newIdx = shelfContentIndex;
    if (contentIndex != lastRendered.contentIndex) return false;
    if (oldIdx == newIdx || oldIdx < 0 || newIdx < 0) return false;
    if (newIdx >= static_cast<int>(shelfBooks.size()) || oldIdx >= static_cast<int>(shelfBooks.size())) return false;

    const int contentTop = metrics.topPadding + metrics.headerHeight + metrics.verticalSpacing;
    const int contentHeight = pageHeight - contentTop - metrics.buttonHintsHeight - metrics.verticalSpacing;
    const int gridWidth = pageWidth - 2 * metrics.contentSidePadding;
    const int cellWidth = gridWidth / GRID_COLS;
    const int cellHeight = getCellHeight(cellWidth);
    const int rowStride = cellHeight + GRID_ROW_GAP;
    const int visibleRows = getVisibleRows(cellHeight, contentHeight);
    // The move must not scroll (renderShelfBooksView would adjust shelfScrollRow).
    const int newRow = newIdx / GRID_COLS;
    if (newRow < shelfScrollRow || newRow >= shelfScrollRow + visibleRows) return false;
    if (shelfScrollRow != lastRendered.shelfScrollRow) return false;

    // The border ring never overlaps cell content, so the move is just erase + draw.
    for (const int idx : {oldIdx, newIdx}) {
      const int row = idx / GRID_COLS;
      const int col = idx % GRID_COLS;
      const int cellX = metrics.contentSidePadding + col * cellWidth;
      const int cellY = contentTop + (row - shelfScrollRow) * rowStride;
      drawGridSelectionBorder(cellX, cellY, cellWidth, cellHeight, idx == newIdx);
    }
    return true;
  }

  // Main view: index 0 is the tab bar -- entering/leaving it changes the tab bar highlight, so
  // only moves between two real items qualify.
  const int oldIdx = lastRendered.contentIndex;
  const int newIdx = contentIndex;
  if (oldIdx == newIdx || oldIdx < 1 || newIdx < 1) return false;

  const int tabBarY = metrics.topPadding + metrics.headerHeight;
  const int contentTop = tabBarY + metrics.tabBarHeight + metrics.verticalSpacing;
  const int contentHeight = pageHeight - contentTop - metrics.buttonHintsHeight - metrics.verticalSpacing;

  if (selectedTab == 0) {
    if (newIdx > static_cast<int>(recentBooks.size()) || oldIdx > static_cast<int>(recentBooks.size())) return false;
    const int gridWidth = pageWidth - 2 * metrics.contentSidePadding;
    const int cellWidth = gridWidth / GRID_COLS;
    const int cellHeight = getCellHeight(cellWidth);
    const int rowStride = cellHeight + GRID_ROW_GAP;
    const int visibleRows = getVisibleRows(cellHeight, contentHeight);
    // The move must not scroll (renderBooksTab would adjust scrollRow).
    const int newRow = (newIdx - 1) / GRID_COLS;
    if (newRow < scrollRow || newRow >= scrollRow + visibleRows) return false;
    if (scrollRow != lastRendered.scrollRow) return false;

    // The border ring never overlaps cell content, so the move is just erase + draw.
    for (const int idx : {oldIdx - 1, newIdx - 1}) {
      const int row = idx / GRID_COLS;
      const int col = idx % GRID_COLS;
      const int cellX = metrics.contentSidePadding + col * cellWidth;
      const int cellY = contentTop + (row - scrollRow) * rowStride;
      drawGridSelectionBorder(cellX, cellY, cellWidth, cellHeight, idx == newIdx - 1);
    }
    return true;
  }

  // Shelves list rows.
  if (newIdx > static_cast<int>(shelves.size()) || oldIdx > static_cast<int>(shelves.size())) return false;
  const int rowHeight = metrics.listWithSubtitleRowHeight;
  const int visibleItems = std::max(1, contentHeight / rowHeight);
  auto scrollOffsetFor = [visibleItems](const int selectedItem) {
    return selectedItem >= visibleItems ? selectedItem - visibleItems + 1 : 0;
  };
  if (scrollOffsetFor(newIdx - 1) != scrollOffsetFor(oldIdx - 1)) return false;
  const int scrollOffset = scrollOffsetFor(newIdx - 1);

  if (fcm) {
    renderer.prewarmText(UI_10_FONT_ID, (shelves[oldIdx - 1].folderName + ' ' + shelves[newIdx - 1].folderName).c_str(),
                         1 << EpdFontFamily::BOLD);
  }
  for (const int idx : {oldIdx - 1, newIdx - 1}) {
    const int itemY = contentTop + (idx - scrollOffset) * rowHeight;
    // Clear the full row footprint including the selection highlight's -6/-4 overhang.
    renderer.fillRect(metrics.contentSidePadding - 6, itemY - 4, pageWidth - 2 * metrics.contentSidePadding + 12,
                      rowHeight + 8, false);
    drawShelfRow(idx, itemY, idx == newIdx - 1);
  }
  if (fcm) fcm->clearCache();
  return true;
}

void RecentBooksActivity::render(RenderLock&&) {
  if (tryPartialSelectionRedraw()) {
    lastRendered.contentIndex = contentIndex;
    lastRendered.shelfContentIndex = shelfContentIndex;
    renderer.displayBuffer();
    return;
  }

  renderer.clearScreen();

  const auto pageWidth = renderer.getScreenWidth();
  const auto pageHeight = renderer.getScreenHeight();
  const auto& metrics = UITheme::getInstance().getMetrics();

  if (openShelfIndex >= 0 && openShelfIndex < static_cast<int>(shelves.size())) {
    GUI.drawHeader(renderer, Rect{0, metrics.topPadding, pageWidth, metrics.headerHeight},
                   shelves[openShelfIndex].folderName.c_str());

    const int contentTop = metrics.topPadding + metrics.headerHeight + metrics.verticalSpacing;
    const int contentHeight = pageHeight - contentTop - metrics.buttonHintsHeight - metrics.verticalSpacing;

    renderShelfBooksView(contentTop, contentHeight);

    const auto labels = mappedInput.mapLabels(tr(STR_BACK), tr(STR_SELECT), tr(STR_DIR_UP), tr(STR_DIR_DOWN));
    GUI.drawButtonHints(renderer, labels.btn1, labels.btn2, labels.btn3, labels.btn4);

    lastRendered = {true, openShelfIndex, selectedTab, contentIndex, scrollRow, shelfContentIndex, shelfScrollRow};
    renderer.displayBuffer();
    return;
  }

  GUI.drawHeader(renderer, Rect{0, metrics.topPadding, pageWidth, metrics.headerHeight}, tr(STR_MENU_RECENT_BOOKS));

  std::vector<TabInfo> tabs;
  tabs.reserve(TAB_COUNT);
  tabs.push_back({tr(STR_TAB_BOOKS), selectedTab == 0});
  tabs.push_back({tr(STR_TAB_SHELVES), selectedTab == 1});
  const int tabBarY = metrics.topPadding + metrics.headerHeight;
  GUI.drawTabBar(renderer, Rect{0, tabBarY, pageWidth, metrics.tabBarHeight}, tabs, contentIndex == 0);

  const int contentTop = tabBarY + metrics.tabBarHeight + metrics.verticalSpacing;
  const int contentHeight = pageHeight - contentTop - metrics.buttonHintsHeight - metrics.verticalSpacing;

  if (selectedTab == 0) {
    renderBooksTab(contentTop, contentHeight);
  } else {
    renderShelvesTab(contentTop, contentHeight);
  }

  const auto labels = mappedInput.mapLabels(tr(STR_HOME), tr(STR_SELECT), tr(STR_DIR_UP), tr(STR_DIR_DOWN));
  GUI.drawButtonHints(renderer, labels.btn1, labels.btn2, labels.btn3, labels.btn4);

  lastRendered = {true, openShelfIndex, selectedTab, contentIndex, scrollRow, shelfContentIndex, shelfScrollRow};
  renderer.displayBuffer();
}
